spring:
  application:
    name: gateway-server
  config:
    import: configserver:http://localhost:8888
  cloud:
    config:
      fail-fast: true
    gateway:
      default-filters:
#        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
#      globalcors:
#        cors-configurations:
#          '[/**]':
#            allowedOrigins: "*"
#            allowedMethods: "*"
#            allowedHeaders: "*"
#            allowCredentials: true
      routes:
        - id: users
          uri: lb://user-service
          predicates:
            - Path=/users/**
          filters:
            - StripPrefix=1
          metadata:
            cors:
              allowedOrigins: 'http://localhost:3000'
              allowedMethods: '*'
              allowedHeaders: '*'


